{% set version = "0.2.1" %}
{% set build = 0 %}

package:
  name: memestra
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/memestra/memestra-{{ version }}.tar.gz
  sha256: eac8707fd0680df64ccb48ad3fc7ac34fe28bfa7f0e8b2693b763965a8700d9c

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - memestra = memestra.memestra:run
    - memestra-cache = memestra.caching:run

requirements:
  host:
    - python >=3.4.0
    - pip
  run:
    - python >=3.4.0
    - gast
    - beniget
    - nbformat
    - nbconvert
    - pyyaml
    - frilouz ==0.0.2

test:
  imports:
    - memestra
  commands:
    - memestra --help

about:
  home: https://github.com/QuantStack/memestra
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python checker for places where deprecated functions are called.
  description: |
    Memestra checks code for places where deprecated functions are called.
  doc_url: https://github.com/QuantStack/memestra
  dev_url: https://github.com/QuantStack/memestra

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - marimeireles
