{% set version = "0.0.7" %}
{% set build = 0 %}

package:
  name: memestra
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/memestra/memestra-{{ version }}.tar.gz
  sha256: 562c2b0c521313d873ec6aa8c7ef3c673d9779c1243067192ed2ead8b2386997

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - memestra = memestra.memestra:run
    - memestra-cache = memestra.caching:run

requirements:
  host:
    - python >=3.4.0
    - pip
  run:
    - python
    - gast
    - beniget
    - nbformat
    - nbconvert
    - pyyaml

test:
  imports:
    - memestra
  commands:
    - memestra --help

about:
  home: https://github.com/QuantStack/memestra
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python checker for places where deprecated functions are called.
  description: |
    Memestra checks code for places where deprecated functions are called.
  doc_url: https://github.com/QuantStack/memestra
  dev_url: https://github.com/QuantStack/memestra

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - marimeireles
